name: Build and Release BMCC SOT Pack

on:
  workflow_dispatch:

jobs:
  build-sot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read event number and version
        run: |
          # Event number from root file
          EVENT_NUM=$(cat bmccEventNumber.txt)
          
          # Version number from inside pack folder
          VERSION_FILE="sotPack/version.txt"
          if [ ! -f "$VERSION_FILE" ]; then
              echo "1" > "$VERSION_FILE"
          fi
          VERSION=$(cat "$VERSION_FILE")

          echo "EVENT_NUM=$EVENT_NUM" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update readme.txt
        run: |
          echo "Hi, this pack uses FAN-MADE assets and stolen ones from MCCI and MCC.

          We do not claim ownership of any of the assets used, taking assets from this pack is allowed however do not claim it is your own. 

          This pack is for BMCC $EVENT_NUM with version $VERSION" > sotPack/readme.txt"

      - name: Create SOT ZIP (contents only, exclude version.txt)
        run: |
          rm -f BMCC-sot.zip
          cd sotPack
          zip -r ../BMCC-sot.zip . -x "version.txt" ".git/*" ".github/*"

      - name: Generate SHA-1 hash
        run: |
          sha1sum BMCC-sot.zip | awk '{ print $1 }' > BMCC-sot.hash.txt

      - name: Upload SOT ZIP and hash to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sotLatest
          files: |
            BMCC-sot.zip
            BMCC-sot.hash.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        run: |
          NEXT=$((VERSION + 1))
          echo $NEXT > sotPack/version.txt
