name: Build and Release BMCC24 Resource-Pack

on:
  push:
    branches: [ main ]
    tags: [ latest ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all tags

      - name: Create ZIP excluding .git and .github
        run: |
          rm -f BMCC24-main.zip
          zip -r BMCC24-main.zip . -x ".git/*" ".github/*"

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: BMCC24-main.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
