name: SOT Pack

on:
  workflow_dispatch:

concurrency:
  group: sot-pack
  cancel-in-progress: true

jobs:
  build:
    name: Build SOT Pack
    runs-on: ubuntu-latest
    outputs:
      NEXT_VERSION: ${{ steps.get_version.outputs.next_version }}
      EVENT_NUM: ${{ steps.get_version.outputs.event_num }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Precompute event number and SOT version
        id: get_version
        run: |
          EVENT_NUM=$(grep 'eventNumber:' bmccEventNumber.txt | cut -d':' -f2 | tr -d ' ')
          SOT_VERSION=$(grep 'SOT:' bmccEventNumber.txt | awk '{print $2}')
          NEXT_VERSION=$((SOT_VERSION + 1))
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "EVENT_NUM=$EVENT_NUM" >> $GITHUB_OUTPUT

      - name: Generate README.txt
        run: |
          echo "Hi, this pack uses FAN-MADE assets and stolen ones from MCCI and MCC." > sotPack/README.txt
          echo "" >> sotPack/README.txt
          echo "We do not claim ownership of any of the assets used, taking assets from this pack is allowed however do not claim it is your own." >> sotPack/README.txt
          echo "" >> sotPack/README.txt
          echo "This pack is for BMCC ${{ steps.get_version.outputs.event_num }} as version #${{ steps.get_version.outputs.NEXT_VERSION }} of the Sands Of Time Pack" >> sotPack/README.txt

      - name: Create SOT ZIP
        run: |
          rm -f BMCC-sot.zip
          cd sotPack
          zip -r ../BMCC-sot.zip . -x ".git/*" ".github/*"
          cd ..

      - name: Compute SHA-1 hash and save as artifact
        run: |
          SHA1=$(sha1sum BMCC-sot.zip | awk '{ print $1 }')
          echo "$SHA1" > bmcc-sot.hash

      - name: Upload SOT ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sotLatest
          files: BMCC-sot.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload hash artifact
        uses: actions/upload-artifact@v4
        with:
          name: sot-hash
          path: bmcc-sot.hash

  update-version-and-hash:
    name: Update SOT Version and Hash
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download hash artifact
        uses: actions/download-artifact@v4
        with:
          name: sot-hash
          path: .

      - name: Update SOT version and hash in root file
        run: |
          git pull origin main
          SHA1=$(cat bmcc-sot.hash)
          NEXT_VERSION=${{ needs.build.outputs.NEXT_VERSION }}
          EVENT_NUM=${{ needs.build.outputs.EVENT_NUM }}
          sed -i "s/^[[:space:]]*SOT:.*/    SOT: $NEXT_VERSION/" bmccEventNumber.txt
          sed -i "s/^[[:space:]]*SOT_HASH:.*/    SOT_HASH: $SHA1/" bmccEventNumber.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bmccEventNumber.txt
          git commit -m "Increment SOT version to $NEXT_VERSION and update hash"
          git push origin main
