name: Build and Release BMCC24 Resource-Pack

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP excluding .git and .github
        run: |
          rm -f BMCC24-main.zip
          zip -r BMCC24-main.zip . -x ".git/*" ".github/*"

      - name: Create or update GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: BMCC24-main.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
